# Generated by Django 2.1 on 2018-08-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('classify', models.CharField(default='null', max_length=120)),
                ('time', models.CharField(default='null', max_length=60)),
            ],
        ),
    ]
