# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-13 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
