# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20180613_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='classify',
            field=models.CharField(default='null', max_length=120),
        ),
    ]
