# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_filename_classify'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='time',
            field=models.CharField(default='null', max_length=60),
        ),
    ]
